### ISSUE TITLE
It's showing flashing but actually not doing it

### ISSUE THREAD

**Issue by BDhackers009** [bdureau/BearConsole2#2]
Hey sir, I was just trying to change some of your code and add my own firmware to flash my normal esp32. I renamed and added the firmwares bootloader,partition and main firmware in the firmware/esp32 directory and changed file names in the FlashFirmware file. Its showing that its flashing the full firmware 1 by 1. after flashing it when i reboot my esp32 it stays at previous firmware. Is this solveable?

**Comment by bdureau** [comment]
Flashi

> Hey sir, I was just trying to change some of your code and add my own firmware to flash my normal esp32. I renamed and added the firmwares bootloader,partition and main firmware in the firmware/esp32 directory and changed file names in the FlashFirmware file. Its showing that its flashing the full firmware 1 by 1. after flashing it when i reboot my esp32 it stays at previous firmware. Is this solveable?

flashing has been tested with ESP32 wroom board and TTGO board. Which one are you using?

**Comment by BDhackers009** [comment]
I have 3 type of boards:- esp32s3,ESP32 CYD(with display), esp8266, I tried with esp32s3 and the esp32 cyd. 

Very sorry sir for the late response I was sick

**Comment by bdureau** [comment]
This is now fixed for ESP32S3

**Comment by bdureau** [comment]
Issue should now be fixed. Reopen if not

**Comment by BDhackers009** [comment]
Sir where do I get the latest apk? The playstore one is updated? Its showing last updated on September

**Comment by bdureau** [comment]
you can download it from https://github.com/bdureau/BearConsole2/releases/tag/ver2.0.9

**Comment by bdureau** [comment]
Just to let you know I am currently adding all the ESP32 chips that are missing

**Comment by BDhackers009** [comment]
> Just to let you know I am currently adding all the ESP32 chips that are missing

I just downloaded the apk sir. I will try tomorrow and let you know
