### ISSUE TITLE
Project needs open source license

### ISSUE THREAD

**Issue by VanceVagell** [bdureau/BearConsole2#3]
Thank you for making this project available! I plan to use it in a project of mine that also needs to flash ESP32 firmware via an Android app.

Can you please add an open source license to your project, so it's clear what it can be used for? (My project is GPL3, but feel free to use whatever works for you.)

Thank you!

**Comment by bdureau** [comment]
I have added the licence. I would be interrested if you make any sugestion and/or modify it for other ESP32 chips

**Comment by bdureau** [comment]
issue solved

**Comment by bdureau** [comment]
Just out of interrest which ESP32 are you trying to flash? Just asking because I am trying to have them all working

**Comment by VanceVagell** [comment]
Hey there. I'm using it to program ESP32-WROOM modules. It doesn't always
work and I haven't pinned down the cause yet, but it may be some difference
in how the dev boards are manufactured. The slimmed down version I'm using
is here:

https://github.com/VanceVagell/kv4p-ht/tree/main/android-src/KV4PHT/app/src/main/java/com/vagell/kv4pht/firmware

I removed the dependency you had on your current USB library so it could
work with the one our project already uses, and made a few other small
tweaks.

Thank you for adding the license so we can give appropriate credit!

**Comment by bdureau** [comment]
I might have an idea. I could had a retry mechanism when the block does not get flash correctly. I will work on it in the next few days. Which usb library are you using?

**Comment by bdureau** [comment]
I am now checking the return code and retry the packet when bad, this should fix your issue

**Comment by VanceVagell** [comment]
Your improvement was very helpful! I modified it slightly to loop up to 10 times on a failed write, but otherwise kept it the same as your patch. For reference, here's our fork of your project as part of our own:

https://github.com/VanceVagell/kv4p-ht/tree/main/android-src/KV4PHT/app/src/main/java/com/vagell/kv4pht/firmware

It's a ham radio accessory that plugs into an Android phone and turns it into a handheld radio transceiver. :) Your library helps people patch new firmware easily without having to hook up to a computer. Thanks for providing it as open source!

**Comment by bdureau** [comment]
> Your improvement was very helpful! I modified it slightly to loop up to 10 times on a failed write, but otherwise kept it the same as your patch. For reference, here's our fork of your project as part of our own:
> 
> https://github.com/VanceVagell/kv4p-ht/tree/main/android-src/KV4PHT/app/src/main/java/com/vagell/kv4pht/firmware
> 
> It's a ham radio accessory that plugs into an Android phone and turns it into a handheld radio transceiver. :) Your library helps people patch new firmware easily without having to hook up to a computer. Thanks for providing it as open source!

Glad that it can help others
